### ISSUE TITLE
README references to include git

### ISSUE THREAD

**Issue by johanek** [johanek/johanek-redmine#20]
The README includes two references to 'include git' in the example usage.

What does the include git statement do? My understanding is include would call another module, in this case called git. It doesn't manage the package in an of itself (which is the intended behaviour from #18), and assumes the user already has a module called git.

If we need to make sure the user has git installed, we should add a module like puppetlabs-git as an optional dependency https://forge.puppetlabs.com/puppetlabs/git

Also, we should be consistent and use the class syntax for importing modules
```
class { 'git': }
```

**Comment by johanek** [comment]
Also, we're installing a lot of junk anyway... wget, gcc etc. should we just add the necessary VCS provider packages to require_packages in install.pp?

**Comment by UnrealQuester** [comment]
You are right. We should not rely on the user having git installed on their system. Or any version control for that matter. The problem is that vcsrepo does not install the required provider. It just emits an error. Perhaps we should just add the required package to the examples. Requiring a module that manages git is overkill in my opinion.

Installing the correct package in install.pp is difficult because the package name might be different from the provider (svn => subversion) or might even vary across linux distributions. I would like to avoid another giant case construct.

My proposal is that we just change
```puppet
include git
```
to
```puppet
package{ 'git': }
```

**Comment by johanek** [comment]
How about a comment in the README explaining the package is a pre-requisite if you're going to install from VCS?

I don't think the case construction would be so bad, the packages names are the same on redhat/debian AFAIK. But if we can avoid it, all the better.

**Comment by UnrealQuester** [comment]
Assuming the package names are the same across distributions, a case tree might be a good solution. I also looked in puppetlabs/vcsrepo to see if there was an option to install the packages. There is not. It turns out it is even worse: There is no autorequire for the package (git beeing an exeption). So puppet might decide to run the vcsrepo stuff before actually installing the correct packages. We now have the two options you mentioned:

A. Tell the users to install the package themselves and have them make sure it gets required by redmine. Also update examples accordingly.

B. Add a case construct to get the correct package name, install it, and require it in vcsrepo.

Option A makes it easy for us, but harder for the user. They have to install additional packages and manage their require order properly. If they don't, they will get a huge flood of errors from failed dependencies. I would like to implement option B this weekend. It adds a little extra package management to our code so that it will 'just work' for our users.

**Comment by johanek** [comment]
OK, I think there's already a pattern for this with wget & tar in download.pp

**Comment by UnrealQuester** [comment]
I just noticed that this change may break backwards compatibility. Imagine you do not want to use the package from your distribution. You could have already installed it from source. In this case we would override the installation. Having a flag or option to control this behaviour would help, but still break for users that relied on us not installing anything. Vcsrepo only cares about the command itself, not how it got installed (except for git, which will require the package). What do you think about this? The branch install-provider contains my work so far. Should we just merge that into master and up the major version?

**Comment by johanek** [comment]
I think we should prioritise making the module "just work" over supporting software installed outside of package management systems
